In [1]:

import pandas as pd

flight_weather_data = pd.read_csv("/mnt/c/Users/tbrag/OneDrive/Desktop/bda602venv/ML Project/flight_weather_fulldata.csv")

# Count rows where both ori_TMIN and dest_TMIN are not NaN
count_valid = (flight_weather_data['ori_TMIN'].notna() & flight_weather_data['dest_TMIN'].notna()).sum()

print(f"Number of rows where both ori_TMIN and dest_TMIN are not NaN: {count_valid}")

#filter those rows out for models including weather
filtered_data = flight_weather_data[(flight_weather_data['ori_TMIN'].notna()) & (flight_weather_data['dest_TMIN'].notna())]

##export the new table##
filtered_data.to_csv('filtered_flight_weather.csv', index=False)

Number of rows where both ori_TMIN and dest_TMIN are not NaN: 1255864

In [3]:
# List of columns to keep
columns_to_keep = ['FL_DATE','FL_NUMBER','ori_TMIN','ori_TMAX','ori_SNOW','ori_SNWD','ori_AWND','ori_PRCP','dest_TMIN','dest_TMAX','dest_SNOW','dest_SNWD','dest_AWND','dest_PRCP']

# Drop all columns except the specified ones
filtered_flight_weather_edited = filtered_data.drop(columns=flight_weather_data.columns.difference(columns_to_keep))


##export the new table##
filtered_flight_weather_edited.to_csv('filtered_flight_weather_edited.csv', index=False)

In [6]:
# Create binary classifier for delayed flights
condition = (
    (filtered_data['ARR_DELAY'] >= 15) |
    (filtered_data['DEP_DELAY'] >= 15) |
    (filtered_data['CANCELLED'] == 1)
)

# Assign the binary classification to a new column 'DELAYED'
filtered_data.loc[:, 'DELAYED'] = condition.astype(int)

# Display the first 5 rows and check DataFrame info
print(filtered_data.head(5))
print(filtered_data.info())

/tmp/ipykernel_392412/3498618020.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_data.loc[:, 'DELAYED'] = condition.astype(int)

       FL_DATE                 AIRLINE                 AIRLINE_DOT  \
4   2020-02-23        Spirit Air Lines        Spirit Air Lines: NK
10  2021-06-11    Delta Air Lines Inc.    Delta Air Lines Inc.: DL
11  2020-07-31  American Airlines Inc.  American Airlines Inc.: AA
13  2019-11-20    Delta Air Lines Inc.    Delta Air Lines Inc.: DL
16  2022-05-01  Southwest Airlines Co.  Southwest Airlines Co.: WN

   AIRLINE_CODE  DOT_CODE  FL_NUMBER ORIGIN         ORIGIN_CITY DEST  \
4            NK     20416        407    MCO         Orlando, FL  DFW
10           DL     19790       2820    ATL         Atlanta, GA  BDL
11           AA     19805       2107    RDU  Raleigh/Durham, NC  DFW
13           DL     19790       1065    BDL        Hartford, CT  ATL
16           WN     19393       1011    BWI       Baltimore, MD  BDL

                DEST_CITY  ...  ori_PRCP  station_id_y      DATE_y  dest_TMIN  \
4   Dallas/Fort Worth, TX  ...       0.0   USW00003927  2020-02-23       78.0
10           Hartford, CT  ...     122.0   USW00014740  2021-06-11      128.0
11  Dallas/Fort Worth, TX  ...       0.0   USW00003927  2020-07-31      228.0
13            Atlanta, GA  ...       3.0   USW00013874  2019-11-20       61.0
16           Hartford, CT  ...      56.0   USW00014740  2022-05-01       33.0

    dest_TMAX  dest_SNOW  dest_SNWD  dest_AWND  dest_PRCP  DELAYED
4       156.0        0.0        0.0       55.0        8.0        0
10      250.0        0.0        0.0       30.0        0.0        1
11      328.0        0.0        0.0       45.0        0.0        0
13      178.0        0.0        0.0       36.0        0.0        0
16      211.0        0.0        0.0       26.0        0.0        0

[5 rows x 58 columns]
<class 'pandas.core.frame.DataFrame'>
Index: 1255864 entries, 4 to 3052355
Data columns (total 58 columns):
 #   Column                   Non-Null Count    Dtype
---  ------                   --------------    -----
 0   FL_DATE                  1255864 non-null  object
 1   AIRLINE                  1255864 non-null  object
 2   AIRLINE_DOT              1255864 non-null  object
 3   AIRLINE_CODE             1255864 non-null  object
 4   DOT_CODE                 1255864 non-null  int64
 5   FL_NUMBER                1255864 non-null  int64
 6   ORIGIN                   1255864 non-null  object
 7   ORIGIN_CITY              1255864 non-null  object
 8   DEST                     1255864 non-null  object
 9   DEST_CITY                1255864 non-null  object
 10  CRS_DEP_TIME             1255864 non-null  int64
 11  DEP_TIME                 1223362 non-null  float64
 12  DEP_DELAY                1223349 non-null  float64
 13  TAXI_OUT                 1222834 non-null  float64
 14  WHEELS_OFF               1222834 non-null  float64
 15  WHEELS_ON                1222522 non-null  float64
 16  TAXI_IN                  1222522 non-null  float64
 17  CRS_ARR_TIME             1255864 non-null  int64
 18  ARR_TIME                 1222522 non-null  float64
 19  ARR_DELAY                1219802 non-null  float64
 20  CANCELLED                1255864 non-null  float64
 21  CANCELLATION_CODE        33113 non-null    object
 22  DIVERTED                 1255864 non-null  float64
 23  CRS_ELAPSED_TIME         1255857 non-null  float64
 24  ELAPSED_TIME             1219802 non-null  float64
 25  AIR_TIME                 1219802 non-null  float64
 26  DISTANCE                 1255864 non-null  float64
 27  DELAY_DUE_CARRIER        229567 non-null   float64
 28  DELAY_DUE_WEATHER        229567 non-null   float64
 29  DELAY_DUE_NAS            229567 non-null   float64
 30  DELAY_DUE_SECURITY       229567 non-null   float64
 31  DELAY_DUE_LATE_AIRCRAFT  229567 non-null   float64
 32  origin_latitude          1255864 non-null  float64
 33  origin_longitude         1255864 non-null  float64
 34  dest_latitude            1255864 non-null  float64
 35  dest_longitude           1255864 non-null  float64
 36  origin_geometry          1255864 non-null  object
 37  origin_station_id        1255864 non-null  object
 38  ori_station_lat          1255864 non-null  float64
 39  ori_station_long         1255864 non-null  float64
 40  dest_station_id          1255864 non-null  object
 41  station_id_x             1255864 non-null  object
 42  DATE_x                   1255864 non-null  object
 43  ori_TMIN                 1255864 non-null  float64
 44  ori_TMAX                 1255864 non-null  float64
 45  ori_SNOW                 1255864 non-null  float64
 46  ori_SNWD                 1255864 non-null  float64
 47  ori_AWND                 1255864 non-null  float64
 48  ori_PRCP                 1255864 non-null  float64
 49  station_id_y             1255864 non-null  object
 50  DATE_y                   1255864 non-null  object
 51  dest_TMIN                1255864 non-null  float64
 52  dest_TMAX                1255864 non-null  float64
 53  dest_SNOW                1255864 non-null  float64
 54  dest_SNWD                1255864 non-null  float64
 55  dest_AWND                1255864 non-null  float64
 56  dest_PRCP                1255864 non-null  float64
 57  DELAYED                  1255864 non-null  int64
dtypes: float64(37), int64(5), object(16)
memory usage: 565.3+ MB
None

In [12]:
# List of columns to keep
columns_to_keep_two = ['FL_DATE','AIRLINE','FL_NUMBER','ORIGIN','ORIGIN_CITY','DEST','DEST_CITY','DEP_TIME','DEP_DELAY','ARR_DELAY','DISTANCE','DIVERTED','ori_TMIN','ori_TMAX','ori_SNOW','ori_SNWD','ori_AWND','ori_PRCP','dest_TMIN','dest_TMAX','dest_SNOW','dest_SNWD','dest_AWND','dest_PRCP','DELAYED']

# Drop all columns except the specified ones
flight_weather_final= filtered_data.drop(columns=filtered_data.columns.difference(columns_to_keep_two))


##export the new table##
flight_weather_final.to_csv('flight_weather_final.csv', index=False)

flight_weather_final.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1255864 entries, 4 to 3052355
Data columns (total 25 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   FL_DATE      1255864 non-null  object
 1   AIRLINE      1255864 non-null  object
 2   FL_NUMBER    1255864 non-null  int64
 3   ORIGIN       1255864 non-null  object
 4   ORIGIN_CITY  1255864 non-null  object
 5   DEST         1255864 non-null  object
 6   DEST_CITY    1255864 non-null  object
 7   DEP_TIME     1223362 non-null  float64
 8   DEP_DELAY    1223349 non-null  float64
 9   ARR_DELAY    1219802 non-null  float64
 10  DIVERTED     1255864 non-null  float64
 11  DISTANCE     1255864 non-null  float64
 12  ori_TMIN     1255864 non-null  float64
 13  ori_TMAX     1255864 non-null  float64
 14  ori_SNOW     1255864 non-null  float64
 15  ori_SNWD     1255864 non-null  float64
 16  ori_AWND     1255864 non-null  float64
 17  ori_PRCP     1255864 non-null  float64
 18  dest_TMIN    1255864 non-null  float64
 19  dest_TMAX    1255864 non-null  float64
 20  dest_SNOW    1255864 non-null  float64
 21  dest_SNWD    1255864 non-null  float64
 22  dest_AWND    1255864 non-null  float64
 23  dest_PRCP    1255864 non-null  float64
 24  DELAYED      1255864 non-null  int64
dtypes: float64(17), int64(2), object(6)
memory usage: 249.1+ MB

In [10]:
flight_weather_final.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1255864 entries, 4 to 3052355
Data columns (total 25 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   FL_DATE      1255864 non-null  object
 1   AIRLINE      1255864 non-null  object
 2   FL_NUMBER    1255864 non-null  int64
 3   ORIGIN       1255864 non-null  object
 4   ORIGIN_CITY  1255864 non-null  object
 5   DEST         1255864 non-null  object
 6   DEST_CITY    1255864 non-null  object
 7   DEP_TIME     1223362 non-null  float64
 8   DEP_DELAY    1223349 non-null  float64
 9   ARR_DELAY    1219802 non-null  float64
 10  DIVERTED     1255864 non-null  float64
 11  DISTANCE     1255864 non-null  float64
 12  ori_TMIN     1255864 non-null  float64
 13  ori_TMAX     1255864 non-null  float64
 14  ori_SNOW     1255864 non-null  float64
 15  ori_SNWD     1255864 non-null  float64
 16  ori_AWND     1255864 non-null  float64
 17  ori_PRCP     1255864 non-null  float64
 18  dest_TMIN    1255864 non-null  float64
 19  dest_TMAX    1255864 non-null  float64
 20  dest_SNOW    1255864 non-null  float64
 21  dest_SNWD    1255864 non-null  float64
 22  dest_AWND    1255864 non-null  float64
 23  dest_PRCP    1255864 non-null  float64
 24  DELAYED      1255864 non-null  int64
dtypes: float64(17), int64(2), object(6)
memory usage: 249.1+ MB

In [26]:
##change date in  to datetime object
flight_weather_final["FL_DATE"] = pd.to_datetime(flight_weather_final["FL_DATE"])

flight_weather_final['month'] = flight_weather_final['FL_DATE'].dt.month
flight_weather_final['is_weekend'] = flight_weather_final['FL_DATE'].dt.dayofweek >= 4  

flight_weather_final["month"] = pd.Categorical(flight_weather_final["month"])
flight_weather_final.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1255864 entries, 4 to 3052355
Data columns (total 27 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   FL_DATE      1255864 non-null  datetime64[ns]
 1   AIRLINE      1255864 non-null  object
 2   FL_NUMBER    1255864 non-null  int64
 3   ORIGIN       1255864 non-null  object
 4   ORIGIN_CITY  1255864 non-null  object
 5   DEST         1255864 non-null  object
 6   DEST_CITY    1255864 non-null  object
 7   DEP_TIME     1223362 non-null  float64
 8   DEP_DELAY    1223349 non-null  float64
 9   ARR_DELAY    1219802 non-null  float64
 10  DIVERTED     1255864 non-null  float64
 11  DISTANCE     1255864 non-null  float64
 12  ori_TMIN     1255864 non-null  float64
 13  ori_TMAX     1255864 non-null  float64
 14  ori_SNOW     1255864 non-null  float64
 15  ori_SNWD     1255864 non-null  float64
 16  ori_AWND     1255864 non-null  float64
 17  ori_PRCP     1255864 non-null  float64
 18  dest_TMIN    1255864 non-null  float64
 19  dest_TMAX    1255864 non-null  float64
 20  dest_SNOW    1255864 non-null  float64
 21  dest_SNWD    1255864 non-null  float64
 22  dest_AWND    1255864 non-null  float64
 23  dest_PRCP    1255864 non-null  float64
 24  DELAYED      1255864 non-null  int64
 25  month        1255864 non-null  category
 26  is_weekend   1255864 non-null  bool
dtypes: bool(1), category(1), datetime64[ns](1), float64(17), int64(2), object(5)
memory usage: 251.5+ MB

In [16]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer ##how we handle missing values
from sklearn.compose import ColumnTransformer ##Transform our data features

In [28]:
#extract Numeric Features
numeric_features = flight_weather_final.select_dtypes(
    include=["float","int"]
).drop(columns=["DEP_TIME",'FL_NUMBER','DEP_DELAY','ARR_DELAY','DIVERTED','FL_NUMBER'])

print(numeric_features.head(2))
categorical_features = flight_weather_final.iloc[:,~flight_weather_final.columns.isin(numeric_features.columns.values)]

#one-hot encoding
categorical_features= flight_weather_final.select_dtypes(include=["category", "object",'bool'])
categorical_features.head(2)

    DISTANCE  ori_TMIN  ori_TMAX  ori_SNOW  ori_SNWD  ori_AWND  ori_PRCP  \
4      985.0     117.0     256.0       0.0       0.0      32.0       0.0
10     859.0     222.0     294.0       0.0       0.0      35.0     122.0

    dest_TMIN  dest_TMAX  dest_SNOW  dest_SNWD  dest_AWND  dest_PRCP  DELAYED
4        78.0      156.0        0.0        0.0       55.0        8.0        0
10      128.0      250.0        0.0        0.0       30.0        0.0        1

,AIRLINE,ORIGIN,ORIGIN_CITY,DEST,DEST_CITY,month,is_weekend
4,Spirit Air Lines,MCO,"Orlando, FL",DFW,"Dallas/Fort Worth, TX",2,True
10,Delta Air Lines Inc.,ATL,"Atlanta, GA",BDL,"Hartford, CT",6,True

In [29]:
from sklearn.model_selection import train_test_split
X = flight_weather_final.iloc[:,~flight_weather_final.columns.isin(["DELAYED"])]
y = flight_weather_final["DELAYED"]

X_train, X_test, y_train, y_test = train_test_split(
    X,y,
    shuffle=True,
    random_state=777,
    test_size=0.15
)
X_train.head(2)

,FL_DATE,AIRLINE,FL_NUMBER,ORIGIN,ORIGIN_CITY,DEST,DEST_CITY,DEP_TIME,DEP_DELAY,ARR_DELAY,...,ori_AWND,ori_PRCP,dest_TMIN,dest_TMAX,dest_SNOW,dest_SNWD,dest_AWND,dest_PRCP,month,is_weekend
2528567,2023-01-10,United Air Lines Inc.,2024,SJU,"San Juan, PR",IAD,"Washington, DC",1753.0,-7.0,-15.0,...,12.0,0.0,-38.0,83.0,0.0,0.0,8.0,0.0,1,False
1285308,2021-05-26,Republic Airline,4505,ORD,"Chicago, IL",MCI,"Kansas City, MO",1538.0,-7.0,-27.0,...,52.0,188.0,178.0,311.0,0.0,0.0,29.0,0.0,5,False

In [31]:
numeric_columns =numeric_features.drop(columns=["DELAYED"]).columns.values
categorical_columns = categorical_features.columns.values
numeric_pipe = Pipeline(
    steps=[
        ("imputer", SimpleImputer()),
        ("standardization", StandardScaler())

    ]
)

In [32]:
categorical_pipe = Pipeline(
    steps=[
        ("one-hot-encoding", OneHotEncoder(handle_unknown="ignore"))
    ]
)

In [33]:
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LogisticRegression

preprocessing_pipe = ColumnTransformer(
    [
        ("numeric_pipe",numeric_pipe,numeric_columns),
        ("categorical_pipe", categorical_pipe, categorical_columns)
    ]
)
model = Pipeline(
    [("Preprocessing",preprocessing_pipe),
     ("regression_model", LogisticRegression())

    ]
    
)

In [35]:
from sklearn.metrics import accuracy_score, classification_report

model.fit(X_train,y_train)

y_pred = model.predict(X_test)

#Evaluate
accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)

In [36]:
print(accuracy)
print(report)

0.757522029939484
              precision    recall  f1-score   support

           0       0.76      0.99      0.86    142150
           1       0.56      0.05      0.10     46230

    accuracy                           0.76    188380
   macro avg       0.66      0.52      0.48    188380
weighted avg       0.71      0.76      0.67    188380

In [38]:
delayed_counts = flight_weather_final['DELAYED'].value_counts()
print(delayed_counts)

DELAYED
0    947267
1    308597
Name: count, dtype: int64